auth              = "bitcoin:bitcoin"
daemon_rpc_addr   = "bitcoind:18443"
daemon_p2p_addr   = "bitcoind:18444"
daemon-dir        = "/bitcoin-data/.bitcoin"
db_dir            = "/electrs-data"
network           = "regtest"
electrum_rpc_addr = "0.0.0.0:50001"
log_filters       = "INFO"
